# Publish all joint states -----------------------------------
joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
    publish_rate: 500

# Quad Controller ---------------------------------------
joint_controller:
  ros__parameters:
    type: quad_controller/QuadController
    joints: ['0','1','2','3','4','5','6','7','8','9','10','11']
    joint_command_topic: ''

contact_state_publisher:
  ros__parameters:
    update_rate: 500
