<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nmpc_controller</name>
  <version>0.0.0</version>
  <description>The nmpc_controller package</description>

  <maintainer email="yanhaoy@andrew.cmu.edu">Yanhao Yang</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>quad_msgs</depend>
  <depend>quad_utils</depend>
  <depend>grid_map_core</depend>
  <depend>grid_map_ros</depend>
  <depend>eigen</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
